INFO  @ Wed, 05 Jul 2023 18:47:06: 
# Command line: callpeak -t data/bam/SRR8315175.bam -c data/bam/SRR8315192.bam -f BAM -g hs --keep-dup all -q 0.05 -n SRR8315175 --bdg --SPMR --outdir output/macs2/SRR8315175
# ARGUMENTS LIST:
# name = SRR8315175
# format = BAM
# ChIP-seq file = ['data/bam/SRR8315175.bam']
# control file = ['data/bam/SRR8315192.bam']
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is off
# Paired-End mode is off
# MACS will save fragment pileup signal per million reads
 
INFO  @ Wed, 05 Jul 2023 18:47:06: #1 read tag files... 
INFO  @ Wed, 05 Jul 2023 18:47:06: #1 read treatment tags... 
INFO  @ Wed, 05 Jul 2023 18:47:08:  1000000 
INFO  @ Wed, 05 Jul 2023 18:47:10:  2000000 
INFO  @ Wed, 05 Jul 2023 18:47:12:  3000000 
INFO  @ Wed, 05 Jul 2023 18:47:13:  4000000 
INFO  @ Wed, 05 Jul 2023 18:47:15:  5000000 
INFO  @ Wed, 05 Jul 2023 18:47:17:  6000000 
INFO  @ Wed, 05 Jul 2023 18:47:19:  7000000 
INFO  @ Wed, 05 Jul 2023 18:47:20:  8000000 
INFO  @ Wed, 05 Jul 2023 18:47:22:  9000000 
INFO  @ Wed, 05 Jul 2023 18:47:24:  10000000 
INFO  @ Wed, 05 Jul 2023 18:47:25:  11000000 
INFO  @ Wed, 05 Jul 2023 18:47:27:  12000000 
INFO  @ Wed, 05 Jul 2023 18:47:29:  13000000 
INFO  @ Wed, 05 Jul 2023 18:47:31:  14000000 
INFO  @ Wed, 05 Jul 2023 18:47:32:  15000000 
INFO  @ Wed, 05 Jul 2023 18:47:34:  16000000 
INFO  @ Wed, 05 Jul 2023 18:47:36:  17000000 
INFO  @ Wed, 05 Jul 2023 18:47:37:  18000000 
INFO  @ Wed, 05 Jul 2023 18:47:39:  19000000 
INFO  @ Wed, 05 Jul 2023 18:47:40: 19412922 reads have been read. 
INFO  @ Wed, 05 Jul 2023 18:47:40: #1.2 read input tags... 
INFO  @ Wed, 05 Jul 2023 18:47:42:  1000000 
INFO  @ Wed, 05 Jul 2023 18:47:44:  2000000 
INFO  @ Wed, 05 Jul 2023 18:47:45:  3000000 
INFO  @ Wed, 05 Jul 2023 18:47:47:  4000000 
INFO  @ Wed, 05 Jul 2023 18:47:49:  5000000 
INFO  @ Wed, 05 Jul 2023 18:47:50:  6000000 
INFO  @ Wed, 05 Jul 2023 18:47:52:  7000000 
INFO  @ Wed, 05 Jul 2023 18:47:54:  8000000 
INFO  @ Wed, 05 Jul 2023 18:47:56:  9000000 
INFO  @ Wed, 05 Jul 2023 18:47:57:  10000000 
INFO  @ Wed, 05 Jul 2023 18:47:59:  11000000 
INFO  @ Wed, 05 Jul 2023 18:48:01:  12000000 
INFO  @ Wed, 05 Jul 2023 18:48:02:  13000000 
INFO  @ Wed, 05 Jul 2023 18:48:04:  14000000 
INFO  @ Wed, 05 Jul 2023 18:48:06:  15000000 
INFO  @ Wed, 05 Jul 2023 18:48:08:  16000000 
INFO  @ Wed, 05 Jul 2023 18:48:09:  17000000 
INFO  @ Wed, 05 Jul 2023 18:48:11:  18000000 
INFO  @ Wed, 05 Jul 2023 18:48:13:  19000000 
INFO  @ Wed, 05 Jul 2023 18:48:13: 19309861 reads have been read. 
INFO  @ Wed, 05 Jul 2023 18:48:13: #1 tag size is determined as 73 bps 
INFO  @ Wed, 05 Jul 2023 18:48:13: #1 tag size = 73.0 
INFO  @ Wed, 05 Jul 2023 18:48:13: #1  total tags in treatment: 19412922 
INFO  @ Wed, 05 Jul 2023 18:48:13: #1  total tags in control: 19309861 
INFO  @ Wed, 05 Jul 2023 18:48:13: #1 finished! 
INFO  @ Wed, 05 Jul 2023 18:48:13: #2 Build Peak Model... 
INFO  @ Wed, 05 Jul 2023 18:48:13: #2 looking for paired plus/minus strand peaks... 
INFO  @ Wed, 05 Jul 2023 18:48:15: #2 number of paired peaks: 6240 
INFO  @ Wed, 05 Jul 2023 18:48:15: start model_add_line... 
INFO  @ Wed, 05 Jul 2023 18:48:15: start X-correlation... 
INFO  @ Wed, 05 Jul 2023 18:48:15: end of X-cor 
INFO  @ Wed, 05 Jul 2023 18:48:15: #2 finished! 
INFO  @ Wed, 05 Jul 2023 18:48:15: #2 predicted fragment length is 189 bps 
INFO  @ Wed, 05 Jul 2023 18:48:15: #2 alternative fragment length(s) may be 189 bps 
INFO  @ Wed, 05 Jul 2023 18:48:15: #2.2 Generate R script for model : output/macs2/SRR8315175/SRR8315175_model.r 
INFO  @ Wed, 05 Jul 2023 18:48:15: #3 Call peaks... 
INFO  @ Wed, 05 Jul 2023 18:48:15: #3 Pre-compute pvalue-qvalue table... 
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpbjmidgf3'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_pvalue_qvalue_table'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpbjmidgf3'
INFO  @ Wed, 05 Jul 2023 18:49:16: #3 In the peak calling step, the following will be performed simultaneously: 
INFO  @ Wed, 05 Jul 2023 18:49:16: #3   Write bedGraph files for treatment pileup (after scaling if necessary)... SRR8315175_treat_pileup.bdg 
INFO  @ Wed, 05 Jul 2023 18:49:16: #3   Write bedGraph files for control lambda (after scaling if necessary)... SRR8315175_control_lambda.bdg 
INFO  @ Wed, 05 Jul 2023 18:49:16: #3   --SPMR is requested, so pileup will be normalized by sequencing depth in million reads. 
INFO  @ Wed, 05 Jul 2023 18:49:16: #3 Call peaks for each chromosome... 
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 1274, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_qscore
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpn8s2ihfg'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpn8s2ihfg'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpsr55rcvt'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpsr55rcvt'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpmrok9smd'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpmrok9smd'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpg8vdmtgz'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpg8vdmtgz'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmp0dwu4a64'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmp0dwu4a64'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpu2jzuv6b'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpu2jzuv6b'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpfhw5beon'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpfhw5beon'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmp2v60zqnt'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmp2v60zqnt'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmp03_i0_0h'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmp03_i0_0h'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpirc1o0rx'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpirc1o0rx'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpnyq1div_'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpnyq1div_'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpwnym8_ro'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpwnym8_ro'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpnpbiqd44'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmpnpbiqd44'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmp7mk46fd7'
Exception ignored in: 'MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria'
Traceback (most recent call last):
  File "MACS2/IO/CallPeakUnit.pyx", line 489, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/hpcfs/users/a1018048/envs/3d1fbf0d79dd5041842db897c580e0ef_/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/mnt/tmp_local/lls_529729/tmp7mk46fd7'
INFO  @ Wed, 05 Jul 2023 18:49:34: #4 Write output xls file... output/macs2/SRR8315175/SRR8315175_peaks.xls 
INFO  @ Wed, 05 Jul 2023 18:49:34: #4 Write peak in narrowPeak format file... output/macs2/SRR8315175/SRR8315175_peaks.narrowPeak 
INFO  @ Wed, 05 Jul 2023 18:49:34: #4 Write summits bed file... output/macs2/SRR8315175/SRR8315175_summits.bed 
INFO  @ Wed, 05 Jul 2023 18:49:34: Done! 
